### ISSUE TITLE
Handle 2d and 3d as word separators

### ISSUE THREAD

**Issue by IceSentry** [rutrum/convert-case#2]
I wanted to use this crate to convert some strings to snake_case, but the strings I wanted to convert need 2d or 3d to be together.

For example:

`CollisionShape2D` should convert to `collision_shape_2d`

**Comment by rutrum** [comment]
Thanks for bringing this up. The algorithm for case conversion starts by determining word boundaries. This can be done in a variety of ways. Unfortunately the exact method is hidden behind the `.from(Case::Snake)`. That is, you can't pick which patterns make word boundaries. This is a good point, and is a fault with its current implementation. Its been a year since I've updated this and I think exposing an API for determining word boundaries might make for a good 0.5.0. Thanks for bringing this up.

So in summary, current methods that determine word boundaries without a delimeter (such as camel case) always put a word boundary before and after numbers. To fix this exact case you'll have to do some manual string contruction (until I update something.)

Also, in an effort to remain language agnostic, I would rather expose word boundaries rather than adding special cases for 2d, 3d, and others.

The problem of what the definition of "cases" are is difficult. I have a side project at https://stringcase.org to try to classify these. It's a difficult problem. Feedback is welcome.

**Comment by IceSentry** [comment]
Interesting, in my case I realised after making this issue that I didn't need to generate the case automatically. Before realising this I simply made a simple `snake_string.replace("2_d", "2d")` after the case conversion.

I looked a bit into this and I'm not even sure how it would be possible to specify a word boundary for this. In the case of 2d and 3d these generally go together, but I can easily imagine having a string where numbers and letters need to be separated. Maybe it could be to split on the second letter after a number. I guess the generalized configuration would be to specify how many letters after a number you want to keep or even specify to only keep a specific letter. Either way, it obviously can't be the default case and as you said would need a way to configure it by the user.

**Comment by rutrum** [comment]
Something like this happens to determine word boundaries for camel/pascal case (not real code):
```{rust}
for a, b in word.iter().window(2) {
   match type(a), type(b) {
        lower, lower => false,
        lower, digit => true,
        digit, digit => false,
        lower, upper => true,
        ....
   }
}
```

What could be done though is something that looks like 
```
"4myVariable_name33Var"
    .delim(Delim::LowerUpper)
    .delim(Delim::DigitLower)
    .delim(Delim::Underscore)
    .to_case(Case::Kebab) // "4my-variable-name33var"
```
Then you could pick from a variety of delimiters for determining word boundaries.  I'm starting to wonder though if this lies outside the scope of this crate.  There are entire crates just for determining word boundaries in language (like https://crates.io/crates/unicode-segmentation) but they are probably too much for simple conversion.  In addition, I imagined my primary audience to be those who develop programming languages, translate from language to language, etc.  In those cases everything is ASCII so there's no need.

If I expose the "word splitting" part of this process, I could also expose the "word joining" part.  Even though I could specify `.to_case(Case::Kebab)` I could instead specifically mention that I want to lowercase each letter and write `.change_case(LetterCase::Lower)` instead.  Then I could write '.join(Delim::Hyphen)` and get the same result.  Of course this would only make sense if exposing these would allow people to construct patterns that aren't common, like a unique format for an identifier like "05-My_custom_case".  This last paragraph is to me a clear overcomplication of the crate, and at that point a person should just write their own string functions, but I thought I would entertain the idea.

But your use case is much more reasonable.  Because word boundaries are so complex that there's an entire crate dedicated to it (again see unicode-segmentation) it might be worth exposing something that allows you to pick how to split identifiers.

**Comment by rutrum** [comment]
This problem is finally solved.  I was able to create the entire case conversion modular, allowing you to specify exactly three things:
* character boundaries to split a multiword identifier into "words"
* a pattern that describes how to mutate the words
* a delimiter to join the words into a single identifier

Thus, you can know do the following to fix your problem.
```
assert_eq!(
  "CollisionShape2D"
    .with_boundaries(&[Boundary::LowerUpper, Boundary::LowerDigit])
    .to_case(Case::Snake),
  "collision_shape_2d"
);
```
You can specify which boundaries you want to split the identifier on before converting into the new case.  Alternatively, you could create your own converter, which would store all the options for a case conversion.
```
let conv = Converter::new()
  .set_boundaries(&[Boundary::LowerUpper, Boundary::LowerDigit])
  .set_pattern(Pattern::LowerCase)
  .set_delim("_");
assert_eq!("collision_shape_2d", conv.convert("CollisionShape2D"));
```

You can see more examples of this in the docs for version 0.5 ([now published](https://docs.rs/convert_case/latest/convert_case/index.html)).  Thank you for this issue.  This was a motivating use case that inspired me to overhaul the conversion process and expose the inner workings of the conversion.
